/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteRouteImport } from './routes/_auth-layout/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthLayoutSignInSplatRouteImport } from './routes/_auth-layout/sign-in/$'
import { Route as AuthLayoutSignUpSplatRouteImport } from './routes/_auth-layout/sign-up/$'
import { Route as ApiAuthSignUpCallbackRouteImport } from './routes/api/auth/sign-up/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutSignInSplatRoute = AuthLayoutSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutSignUpSplatRoute = AuthLayoutSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const ApiAuthSignUpCallbackRoute = ApiAuthSignUpCallbackRouteImport.update({
  id: '/api/auth/sign-up/callback',
  path: '/api/auth/sign-up/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/api/auth/sign-up/callback': typeof ApiAuthSignUpCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/api/auth/sign-up/callback': typeof ApiAuthSignUpCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-layout': typeof AuthLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/_auth-layout/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/_auth-layout/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/api/auth/sign-up/callback': typeof ApiAuthSignUpCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/auth/sign-up/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/auth/sign-up/callback'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout'
    | '/dashboard'
    | '/_auth-layout/sign-in/$'
    | '/_auth-layout/sign-up/$'
    | '/api/auth/sign-up/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRoute
  ApiAuthSignUpCallbackRoute: typeof ApiAuthSignUpCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout/sign-in/$': {
      id: '/_auth-layout/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthLayoutSignInSplatRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_auth-layout/sign-up/$': {
      id: '/_auth-layout/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthLayoutSignUpSplatRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/api/auth/sign-up/callback': {
      id: '/api/auth/sign-up/callback'
      path: '/api/auth/sign-up/callback'
      fullPath: '/api/auth/sign-up/callback'
      preLoaderRoute: typeof ApiAuthSignUpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutSignInSplatRoute: typeof AuthLayoutSignInSplatRoute
  AuthLayoutSignUpSplatRoute: typeof AuthLayoutSignUpSplatRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutSignInSplatRoute: AuthLayoutSignInSplatRoute,
  AuthLayoutSignUpSplatRoute: AuthLayoutSignUpSplatRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRoute,
  ApiAuthSignUpCallbackRoute: ApiAuthSignUpCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
