/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteRouteImport } from './routes/_auth-layout/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthLayoutSignInSplatRouteImport } from './routes/_auth-layout/sign-in/$'
import { Route as AuthLayoutSignUpSplatRouteImport } from './routes/_auth-layout/sign-up/$'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard/account/index'
import { Route as DashboardPayoutMethodsIndexRouteImport } from './routes/dashboard/payout-methods/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardRequestIndexRouteImport } from './routes/dashboard/request/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutSignInSplatRoute = AuthLayoutSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutSignUpSplatRoute = AuthLayoutSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayoutMethodsIndexRoute =
  DashboardPayoutMethodsIndexRouteImport.update({
    id: '/payout-methods/',
    path: '/payout-methods/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRequestIndexRoute = DashboardRequestIndexRouteImport.update({
  id: '/request/',
  path: '/request/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/payout-methods/': typeof DashboardPayoutMethodsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/request/': typeof DashboardRequestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/payout-methods': typeof DashboardPayoutMethodsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/request': typeof DashboardRequestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-layout': typeof AuthLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth-layout/sign-in/$': typeof AuthLayoutSignInSplatRoute
  '/_auth-layout/sign-up/$': typeof AuthLayoutSignUpSplatRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/payout-methods/': typeof DashboardPayoutMethodsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/request/': typeof DashboardRequestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/account/'
    | '/dashboard/payout-methods/'
    | '/dashboard/profile/'
    | '/dashboard/request/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/account'
    | '/dashboard/payout-methods'
    | '/dashboard/profile'
    | '/dashboard/request'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout'
    | '/dashboard'
    | '/_auth-layout/sign-in/$'
    | '/_auth-layout/sign-up/$'
    | '/dashboard/account/'
    | '/dashboard/payout-methods/'
    | '/dashboard/profile/'
    | '/dashboard/request/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout/sign-in/$': {
      id: '/_auth-layout/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthLayoutSignInSplatRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_auth-layout/sign-up/$': {
      id: '/_auth-layout/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthLayoutSignUpSplatRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payout-methods/': {
      id: '/dashboard/payout-methods/'
      path: '/payout-methods'
      fullPath: '/dashboard/payout-methods/'
      preLoaderRoute: typeof DashboardPayoutMethodsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/request/': {
      id: '/dashboard/request/'
      path: '/request'
      fullPath: '/dashboard/request/'
      preLoaderRoute: typeof DashboardRequestIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutSignInSplatRoute: typeof AuthLayoutSignInSplatRoute
  AuthLayoutSignUpSplatRoute: typeof AuthLayoutSignUpSplatRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutSignInSplatRoute: AuthLayoutSignInSplatRoute,
  AuthLayoutSignUpSplatRoute: AuthLayoutSignUpSplatRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardPayoutMethodsIndexRoute: typeof DashboardPayoutMethodsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardRequestIndexRoute: typeof DashboardRequestIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardPayoutMethodsIndexRoute: DashboardPayoutMethodsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardRequestIndexRoute: DashboardRequestIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
